server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/users/**
        - id: service-movie
          uri: lb://service-movie
          predicates:
            - Path=/movies/**
        - id: service-booking
          uri: lb://service-booking
          predicates:
            - Path=/booking/**
        - id: service-showtime
          uri: lb://service-showtime
          predicates:
            - Path=/showtime/**
